package gov.hhs.cms.dsh.sim.ee.hubc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-07-09T11:21:38.400-04:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://hubc.ee.sim.dsh.cms.hhs.gov", name = "HubConnectivityPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HubConnectivityPortType {

    @WebMethod(operationName = "HubConnectivityCheck")
    @WebResult(name = "HubConnectivityResponse", targetNamespace = "http://hubc.ee.sim.dsh.cms.hhs.gov", partName = "body")
    public HubConnectivityResponseType hubConnectivityCheck(
        @WebParam(partName = "body", name = "HubConnectivityRequest", targetNamespace = "http://hubc.ee.sim.dsh.cms.hhs.gov")
        java.lang.Object body
    );
}
