package gov.hhs.cms.dsh.sim.ee.hubc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * HIX DSH Hub Connectivity Service
 * 		
 *
 * This class was generated by Apache CXF 3.1.0
 * 2015-07-09T11:21:38.434-04:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "HubConnectivityService", 
                  wsdlLocation = "file:/C:/Simeon/projects/dropwizard-projects/iws-java-vendor/connectivity-test/src/main/resources/META-INF/ConnectivityTest.wsdl",
                  targetNamespace = "http://hubc.ee.sim.dsh.cms.hhs.gov") 
public class HubConnectivityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hubc.ee.sim.dsh.cms.hhs.gov", "HubConnectivityService");
    public final static QName HubConnectivityPortType = new QName("http://hubc.ee.sim.dsh.cms.hhs.gov", "HubConnectivityPortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Simeon/projects/dropwizard-projects/iws-java-vendor/connectivity-test/src/main/resources/META-INF/ConnectivityTest.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HubConnectivityService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Simeon/projects/dropwizard-projects/iws-java-vendor/connectivity-test/src/main/resources/META-INF/ConnectivityTest.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HubConnectivityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HubConnectivityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HubConnectivityService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HubConnectivityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HubConnectivityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HubConnectivityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HubConnectivityPortType
     */
    @WebEndpoint(name = "HubConnectivityPortType")
    public HubConnectivityPortType getHubConnectivityPortType() {
        return super.getPort(HubConnectivityPortType, HubConnectivityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HubConnectivityPortType
     */
    @WebEndpoint(name = "HubConnectivityPortType")
    public HubConnectivityPortType getHubConnectivityPortType(WebServiceFeature... features) {
        return super.getPort(HubConnectivityPortType, HubConnectivityPortType.class, features);
    }

}
